# Define Base Colors

# Colors from CCCM design guidelines
cccmcolors <- list(
    bluesapphire = "#1B657C",
    balticsea = "#2C2C2C",
    burntsienna = "#EC6B4D",
    ecruwhite = "#F5F3E8",
    mossgreen = "#BBDFBB",
    moonstoneblue = "#6FC5BC",
    steelblue = "#4595AD"
)

# Generate color_variables.css

css_colors <- paste0("  --cccm-", names(cccmcolors), ": ", unname(unlist(cccmcolors)), ";")

warning <-
    "/*! This file is autogenerated in data-raw/colors.
    R Do not manually edit */"

fileConn <- file("inst/resources/css/color_variables.css")
writeLines(c(warning, ":root {", css_colors, "}"), fileConn)
close(fileConn)

# Generate SCSS variables

scss_colors <- paste0("$cccm-", names(cccmcolors), ": ", unname(unlist(cccmcolors)), ";")

warning <- "// This file is autogenerated in data-raw/colors.R. Do not manually edit"

fileConn <- file("data-raw/scss/_colors.scss")
writeLines(c(warning, scss_colors), fileConn)
close(fileConn)
